events {
    worker_connections 1024;
}

http {

    # Upstream hacia svc-rooms (nombre del servicio en la red de Docker)
    upstream svc-rooms {
        server svc-rooms:8081;
    }

    # Upstream hacia svc-reservations (nombre del servicio en la red de Docker)
    upstream svc-reservations {
        server svc-reservations:8082;
    }

    server {
        listen 80;

        # Enruta todo lo relacionado con habitaciones hacia svc-rooms
        location /api/v1/rooms {
            proxy_pass http://svc-rooms;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Enruta todo lo relacionado con reservas hacia svc-reservations
        location /api/v1/reservations {
            proxy_pass http://svc-reservations;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Endpoint de salud del propio gateway
        location /health {
            return 200 '{"status":"UP","service":"api-gateway"}';
            add_header Content-Type application/json;
        }
    }
}
